name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    name: Typecheck client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8

  test:
    name: Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start IPFS Cluster
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Wait for IPFS Cluster ready
        run: sleep 10

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Run tests
        run: npm run test

      - name: Stop IPFS Cluster
        if: always()
        run: docker-compose -f "docker-compose.yml" down
